# Generated by Django 3.2 on 2021-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Marshmello', 'Marshmello'), ('Cake', 'Cake'), ('Chesscake', 'Chesscake'), ('Capcake', 'Capcake')], default='Cake', max_length=60, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
