# Generated by Django 3.2 on 2021-06-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='cake_image/err.png', upload_to='cake_image', verbose_name='Изображения'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
