# Generated by Django 3.2 on 2021-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210819_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Chesscake', 'Chesscake'), ('Marshmello', 'Marshmello'), ('Capcake', 'Capcake'), ('Cake', 'Cake')], default='Cake', max_length=60, verbose_name='Category'),
        ),
    ]
