# Generated by Django 3.2 on 2021-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210613_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Торт', 'Торт'), ('Маршмеллоу', 'Маршмеллоу'), ('Капкейки', 'Капкейки'), ('Чизкейк', 'Чизкейк')], default='Торт', max_length=40, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Названия'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
