# Generated by Django 3.2 on 2021-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisment/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date of published')),
            ],
            options={
                'db_table': 'product_advertisement',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Marshmello', 'Marshmello'), ('Cake', 'Cake'), ('Capcake', 'Capcake'), ('Chesscake', 'Chesscake')], default='Cake', max_length=60, verbose_name='Category'),
        ),
    ]
