# Generated by Django 3.2 on 2021-09-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210920_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.SlugField(blank='True', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Chesscake', 'Chesscake'), ('Cake', 'Cake'), ('Marshmello', 'Marshmello'), ('Capcake', 'Capcake')], default='Cake', max_length=60, verbose_name='Category'),
        ),
    ]
